import type { SupplementEntry } from "./types";

export const SUPPLEMENTS: SupplementEntry[] = [
  {
    id: "creatine",
    name: "Creatine monohydrate",
    defaultDose: "5 g",
    defaultTiming: "any time, daily, with water",
    evidenceTier: "Strong",
    studyCount: 500,
    goals: ["muscle", "longevity", "focus"],
    symptoms: ["low-strength", "brain-fog"],
    pubmedExample: "PMID: 28615996",
    contraindications: ["chronic kidney disease without clinician oversight"],
  },
  {
    id: "vitamin-d3",
    name: "Vitamin D3",
    defaultDose: "2000 IU",
    defaultTiming: "with breakfast (fat-containing meal)",
    evidenceTier: "Strong",
    studyCount: 300,
    goals: ["energy", "muscle", "longevity"],
    symptoms: ["fatigue", "low-strength"],
    pubmedExample: "PMID: 17634462",
    contraindications: ["hypercalcemia", "sarcoidosis"],
  },
  {
    id: "magnesium-glycinate",
    name: "Magnesium glycinate",
    defaultDose: "300 mg elemental",
    defaultTiming: "evening, 1–2 hours before bed",
    evidenceTier: "Strong",
    studyCount: 120,
    goals: ["energy", "muscle", "longevity", "focus"],
    symptoms: ["poor-sleep", "fatigue"],
    pubmedExample: "PMID: 28445426",
    contraindications: ["severe renal impairment"],
  },
  {
    id: "omega-3",
    name: "Omega-3 (EPA/DHA)",
    defaultDose: "2 g combined EPA+DHA",
    defaultTiming: "with a meal containing fat",
    evidenceTier: "Strong",
    studyCount: 250,
    goals: ["fat-loss", "longevity", "focus"],
    symptoms: ["brain-fog"],
    contraindications: ["bleeding disorders", "anticoagulant therapy without clinician oversight"],
  },
  {
    id: "protein",
    name: "Whey or plant protein",
    defaultDose: "25–40 g per serving",
    defaultTiming: "post-workout or to plug a meal protein gap",
    evidenceTier: "Strong",
    studyCount: 200,
    goals: ["muscle", "fat-loss"],
    symptoms: ["low-strength"],
    pubmedExample: "PMID: 28698222",
    contraindications: ["severe lactose intolerance (whey only)", "milk allergy (whey only)"],
  },
  {
    id: "caffeine-theanine",
    name: "Caffeine + L-theanine",
    defaultDose: "100 mg caffeine + 200 mg L-theanine",
    defaultTiming: "morning or pre-work, not after 2pm",
    evidenceTier: "Moderate",
    studyCount: 40,
    goals: ["focus", "fat-loss", "energy"],
    symptoms: ["brain-fog", "fatigue"],
    pubmedExample: "PMID: 18681988",
    contraindications: ["arrhythmia", "uncontrolled hypertension", "anxiety disorders"],
  },
  {
    id: "rhodiola",
    name: "Rhodiola rosea",
    defaultDose: "200–400 mg standardized extract",
    defaultTiming: "morning, on an empty stomach",
    evidenceTier: "Moderate",
    studyCount: 25,
    goals: ["focus", "energy"],
    symptoms: ["brain-fog", "fatigue"],
    contraindications: ["bipolar disorder", "MAOI use"],
  },
  {
    id: "ashwagandha",
    name: "Ashwagandha (KSM-66)",
    defaultDose: "600 mg",
    defaultTiming: "split AM/PM with food",
    evidenceTier: "Moderate",
    studyCount: 30,
    goals: ["muscle", "focus", "longevity"],
    symptoms: ["poor-sleep", "low-strength"],
    pubmedExample: "PMID: 23439798",
    contraindications: ["pregnancy", "thyroid medication", "autoimmune disease"],
  },
  {
    id: "zinc",
    name: "Zinc",
    defaultDose: "15 mg elemental",
    defaultTiming: "with a meal",
    evidenceTier: "Moderate",
    studyCount: 60,
    goals: ["energy", "longevity"],
    symptoms: ["fatigue"],
    contraindications: ["copper deficiency", "long-term high-dose use"],
  },
  {
    id: "b12",
    name: "B12 (methylcobalamin)",
    defaultDose: "500 mcg",
    defaultTiming: "morning, with or without food",
    evidenceTier: "Strong",
    studyCount: 100,
    goals: ["energy", "focus"],
    symptoms: ["fatigue", "brain-fog"],
    contraindications: [],
  },
  {
    id: "iron",
    name: "Iron (ferrous bisglycinate)",
    defaultDose: "18 mg elemental",
    defaultTiming: "morning, away from coffee, tea, calcium",
    evidenceTier: "Strong",
    studyCount: 80,
    goals: ["energy"],
    symptoms: ["fatigue"],
    contraindications: ["hemochromatosis", "non-deficient state (test ferritin first)"],
  },
  {
    id: "probiotic",
    name: "Multi-strain probiotic",
    defaultDose: "10–25 billion CFU",
    defaultTiming: "with breakfast",
    evidenceTier: "Moderate",
    studyCount: 70,
    goals: ["longevity"],
    symptoms: ["bloating"],
    pubmedExample: "PMID: 24912386",
    contraindications: ["severe immunosuppression"],
  },
  {
    id: "electrolytes",
    name: "Electrolytes (sodium + potassium)",
    defaultDose: "1000 mg sodium + 300 mg potassium",
    defaultTiming: "around training or first thing on keto",
    evidenceTier: "Moderate",
    studyCount: 35,
    goals: ["fat-loss", "energy"],
    symptoms: ["fatigue"],
    contraindications: ["hypertension on sodium-restricted diet", "kidney disease"],
  },
  {
    id: "melatonin",
    name: "Melatonin (low-dose)",
    defaultDose: "0.3–1 mg",
    defaultTiming: "30–45 minutes before bed",
    evidenceTier: "Strong",
    studyCount: 90,
    goals: [],
    symptoms: ["poor-sleep"],
    pubmedExample: "PMID: 23691095",
    contraindications: ["pregnancy", "autoimmune disease", "use in children without clinician oversight"],
  },
];

export function getSupplement(id: string): SupplementEntry {
  const entry = SUPPLEMENTS.find((s) => s.id === id);
  if (!entry) {
    throw new Error(`Unknown supplement id: ${id}`);
  }
  return entry;
}
